// This file is auto-generated by @hey-api/openapi-ts

export type Clients = {
    id: string;
    type: string;
} & {
    attributes: {
        secondName: string;
        firstName: string;
        patronymic: string;
        phoneNumber: string;
        email: string;
        passportSeries: string;
        passportNumber: string;
        issuedBy: string;
        dateOfIssue: string;
    };
};

export type ClientsResponseBody = {
    data: Clients;
};

export type ClientsListResponseBody = {
    data: Array<Clients>;
};

export type ClientsRequestBody = {
    data: {
        type: 'clients';
        attributes: {
            secondName: string;
            firstName: string;
            patronymic: string;
            phoneNumber: string;
            email: string;
            passportSeries: string;
            passportNumber: string;
            issudeBy: string;
        };
    };
};

export type GetAllClientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/clients';
};

export type GetAllClientsErrors = {
    /**
     * Unexpected error
     */
    default: unknown;
};

export type GetAllClientsResponses = {
    /**
     * All clients successfully obtained
     */
    200: ClientsResponseBody;
};

export type GetAllClientsResponse = GetAllClientsResponses[keyof GetAllClientsResponses];

export type CreateClientsData = {
    body: ClientsRequestBody;
    path?: never;
    query?: never;
    url: '/clients';
};

export type CreateClientsErrors = {
    /**
     * Unexpected error
     */
    default: unknown;
};

export type CreateClientsResponses = {
    /**
     * Clients was successfully created
     */
    201: ClientsResponseBody;
};

export type CreateClientsResponse = CreateClientsResponses[keyof CreateClientsResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8000/api' | (string & {});
};